### ISSUE TITLE
cannot use openssl under Guardian OS, error "cannot find entropy source"

### ISSUE THREAD

**Issue by albertxzh** [ituglib/openssl-1.1.1#11]
Hi,

Please help. i am out of idea.

I compiled the openssl 1.1.1t code with nonstop-nsx_g_tandem configuration. the compile process is success. After that, I deploy the openssl program with its dependency libs to Guardian system. I ran opessl program, under openssl prompt, i was trying to connect to a remote server through s_client coomand and get error below. 

0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:C:\Us
ers\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand/drbg_lib.c:5
78:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:C:\Us
ers\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand/drbg_lib.c:5
78:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:C:\Us
ers\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand/drbg_lib.c:5
78:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:C:\Us
ers\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand/drbg_lib.c:5
78:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:C:\Us
ers\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand/drbg_lib.c:5
78:
0:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving
entropy:C:\Users\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand
/drbg_lib.c:335:
0:error:2406B072:random number generator:RAND_DRBG_generate:in error state:C:\Us
ers\azha\Documents\Projects\BackBox\ITUGOPENSSL\openssl\crypto/rand/drbg_lib.c:5
78:
0:error:140A9041:SSL routines:SSL_CTX_new:malloc failure:C:\Users\azha\Documents
\Projects\BackBox\ITUGOPENSSL\openssl\ssl/ssl_lib.c:3223:
error in s_client

Thank you in advance for you rhelp.

Albert

**Comment by albertxzh** [comment]
By the way. It is openssl 1.1.1t version

**Comment by rsbeckerca** [comment]
@albertxzh We think this situation may be resolved at 1.1.1u, but that is uncertain. The situation is that PRNGD must be running on the system where OpenSSL 1.1.1u (NonStop) runs. PRNGD is a HPE coreutils server and is supported by GNSC. There is a similar problem at 3.0.8, but we think it has been resolved at 3.0.9, which is heading to the ITUGLIB webserver shortly.

**Comment by rsbeckerca** [comment]
Preparing to close this issue, unless anyone still as the problem. One week time limit. Note that 1.1.1 goes off support September 2023.

**Comment by albertxzh** [comment]
Thank you, rsbeckerca. In my env, I think that i dont have connection to PRNGD running because there is no $zpls or $zls running. Or do you know how to find whether there is PRNGD running in the system? thank you again for your help.

**Comment by rsbeckerca** [comment]
> Thank you, rsbeckerca. In my env, I think that i dont have connection to PRNGD running because there is no $zpls or $zls running. Or do you know how to find whether there is PRNGD running in the system? thank you again for your help.

PRNGD is part of Coreutils (T1202). From an OSS shell, you can try `ps -ef | fgrep -i prngd`. It should give you something like:
```
SUPER.SUPER        637534442          1 - #stderr  Feb 21      05:01:10 /usr/coreutils/sbin/prngd -d -f /etc/egd-pool tcp/localhost:708
```
if PRNGD is running. The command listed is how to start it, but you need to seed the random data. Since PRNGD is an HPE product, GNSC can help you get it running if it is not running. It should be a Kernel managed process to stay up. If you have access to NSGit (T1198), there are instructions in that product for starting it.

**Comment by albertxzh** [comment]
Got it. Thank you, rsbeckerca.
